### PR TITLE
Optimize 3d Logo - JSW

### PR DESCRIPTION
**Pull request by jeffscottward**
Had to reorder some things to make sense of what was going on. works fine

### CODE REVIEW

**Comment by danfinlay** [comment]
What was the problem?

**Comment by jeffscottward** [comment]
It was recomputing, modding the dom, and painting pixels every millisecond regardless of mouse movement or not because it was always calling requestAnimationFrame regardless of if it needed to.

Either you or Kumavis’ hint at a “shouldUpdate” was key. Thanks!

**Comment by jeffscottward** [comment]
Paint profiler ftw
https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas

**Comment by danfinlay** [comment]
Awesome, thanks!!

**Pull request merged**
